import type { Metadata } from 'next'

import { Container, Header } from '@/app/components'
import { Navigation } from '@/app/components/Styleguide'

import '@/styles/index.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const onClick = () => {}
  return (
    <html lang="de">
      <body>
        <Header />
        <Container>
          <h1 className="headline-t2">Styleguide</h1>
          <Navigation />
        </Container>
        <Container>{children}</Container>
      </body>
    </html>
  )
}
