import type { Metadata } from 'next'

import Header from './components/Header'
import Container from './components/Container'

import '@/styles/index.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <body>
        <Header />
        <Container>{children}</Container>
      </body>
    </html>
  )
}
